### ISSUE TITLE
Float number errror in eigen

### ISSUE THREAD

**Issue by hz-xiaxz** [hz-xiaxz/FFS-julia#21]
Set `AHModel.omega = zeros` will cause strange behaviour of eigen system vectors `U`
```julia
fast_update: Test Failed at /home/xuanzhexia/.julia/dev/FFS-julia/test/Ansatz.jl:31
  Expression: FastFermionSampling.fast_update(orb.U_down, U_downinvs, new_conf_downstr, conf_downstr) ≈ det(orb.U_down[new_conf_down, :]) / det(orb.U_down[conf_down, :])
   Evaluated: 1.110223024625158e-16 ≈ 0.0
```
This issue is related to the float number error of eigen systems `U`
```julia
orb.U_up = [0.5000000000000007 0.0; 0.5 -0.7071067811865476; 0.4999999999999999 0.7071067811865475; 0.4999999999999993 0.0]
orb.U_down = [0.5000000000000007 0.0; 0.5 -0.7071067811865476; 0.4999999999999999 0.7071067811865475; 0.4999999999999993 0.0]
```

**Comment by hz-xiaxz** [comment]
This will not frequently happen with a random series of `omega`

**Comment by hz-xiaxz** [comment]
This can be a small project to investigate!

**Comment by hz-xiaxz** [comment]
- [ ] check if using LU rather than invs will fix this, [ref](https://discourse.julialang.org/t/why-re-use-factorization-a-rather-than-inv-a/113234/7)

**Comment by hz-xiaxz** [comment]
This problem still exists in disorder system

**Comment by GiggleLiu** [comment]
Is the following what you want?
```julia
julia> isapprox(1.110223024625158e-16, 0.0; atol=1e-10)
true
```

The default `≈` uses the relative error at around 0.0:
```julia
julia> eps(0.0)
5.0e-324
```

**Comment by hz-xiaxz** [comment]
Sorry I didn't elaborate this issue, it's not related to the precision of `≈`.

I use `n_vec = normalize([U_x \ B; 1])` in `FFS.jl:31` to perform `lu` decomposition, while this decomposition throws `SingularException` sometimes. I think this is because of the transfer of float number precision in solving `eigensystem`, so I opened this issue. However I'm not 100% sure at this moment. 

Here is a case in which `\` operation will fail:
```julia
julia>U_x
7×7 Matrix{Float64}:
 -0.280936   0.460138  -0.25   0.147961   0.486398   5.46374e-17   0.098312
  0.443327   0.179861  -0.25  -0.44863   -0.018171   5.46374e-17  -0.368015
 -0.162391   0.076964  -0.25   0.163824  -0.468227   2.68818e-17   0.269703
  0.443327  -0.179861  -0.25   0.44863   -0.018171   5.46374e-17  -0.368015
 -0.280936  -0.460138  -0.25  -0.147961   0.486398   5.46374e-17   0.098312
 -0.162391  -0.076964  -0.25  -0.163824  -0.468227   1.98658e-16   0.269703
  0.0        0.0       -0.25   0.0        0.0       -0.5           0.0
julia>B
7-element Vector{Float64}:
 -0.1279879033414819
 -0.2330440908908138
  0.12798790334148186
  0.2330440908908132
  0.10505618754933155
  1.6653345369377348e-16
  0.36103199423229576
julia> U_x\B
ERROR: LinearAlgebra.SingularException(7)
```
more readable in snapshot
![image](https://github.com/user-attachments/assets/50626204-d619-4597-8815-ab314db4d51b)

**Comment by hz-xiaxz** [comment]
I think the `lu` decomposition in julia already used pivoting technique for improving numerical stability? Is there any other technique useful (like simply adding the precision of float number?) to alleviate it? or I'll just throw away these blow-up numbers since I'm writing a statistical algorithm?

**Comment by hz-xiaxz** [comment]
Due to this instability(probably), the samples behave like that (each sample on screen is averaged within 100 steps, so the total sample number is $1000*100=1e5$):
![image](https://github.com/user-attachments/assets/4bc13e3e-ee05-4ea6-8aea-12534a7f8933)

**Comment by hz-xiaxz** [comment]
try to use sparse matrix, [ref](https://discourse.julialang.org/t/too-much-matrix-inverse-error/70974)

**Comment by hz-xiaxz** [comment]
> It is expected, the condition number of Ux is too large:
> 
> ```julia
> julia> LinearAlgebra.cond(U_x)
> 1.1227427389453728e17
> ```

Do you think that using `sparse` matrix or using other eigensolver routine like [ArnoldiMethod.jl](https://julialinearalgebra.github.io/ArnoldiMethod.jl/dev/) or [KrylovKit.jl](https://jutho.github.io/KrylovKit.jl/latest/man/eig/#KrylovKit.eigsolve) will help to alleviate this issue?

**Comment by hz-xiaxz** [comment]
this is not a issue in eigen, it is an issue in the pivoting technique of gaussian elimination.

In the previous code, I *a prior* choose the normalized vector's last element to be 1, which is numerically unstable since other elements can be comparably larger than it. 

Maybe try to use `nullspace` and others

**Comment by hz-xiaxz** [comment]
close with #47
