### ISSUE TITLE
Implement Lanczos Algorithm

### ISSUE THREAD

**Issue by hz-xiaxz** [hz-xiaxz/FFS-julia#28]
check [this](https://github.com/shifushuimenu/lanczos-julia) for reference

**Comment by GiggleLiu** [comment]
Hey, please do not implement your own Lanczos, check this out:
https://github.com/Jutho/KrylovKit.jl

If you have time, you may help improving the above package by adding the block feature.
https://github.com/Jutho/KrylovKit.jl/issues/87

**Comment by hz-xiaxz** [comment]
> Hey, please do not implement your own Lanczos, check this out: https://github.com/Jutho/KrylovKit.jl
> 
> If you have time, you may help improving the above package by adding the block feature. [Jutho/KrylovKit.jl#87](https://github.com/Jutho/KrylovKit.jl/issues/87)

Thanks, I will check it

**Comment by hz-xiaxz** [comment]
This is unnecessary
